[build]
  publish = "netlify-site"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/beans"
  to = "/.netlify/functions/beans"
  status = 200

[[redirects]]
  from = "/api/translate"
  to = "/.netlify/functions/translate"
  status = 200
